### ISSUE TITLE
`app-laptop/tlp-9999-r1` now fails

### ISSUE THREAD

**Issue by mid-kid** [dywisor/tlp-portage#20]
Error log:
```
Traceback (most recent call last):
  File "/usr/lib/portage/python3.6/doins.py", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.6/doins.py", line 602, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/python3.6/doins.py", line 450, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.6/doins.py", line 386, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.6/doins.py", line 195, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'README'
 * ERROR: app-laptop/tlp-9999-r1::tlp failed (install phase):
 *   dodoc failed
 * 
 * If you need support, post the output of `emerge --info '=app-laptop/tlp-9999-r1::tlp'`,
 * the complete build log and the output of `emerge -pqv '=app-laptop/tlp-9999-r1::tlp'`.
 * The complete build log is located at '/var/tmp/portage/app-laptop/tlp-9999-r1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-laptop/tlp-9999-r1/temp/environment'.
 * Working directory: '/var/tmp/portage/app-laptop/tlp-9999-r1/work/tlp-9999'
 * S: '/var/tmp/portage/app-laptop/tlp-9999-r1/work/tlp-9999'
```

**Comment by dywisor** [comment]
Hi,

thanks for reporting.

The README file has been moved upstream, I've changed the ebuild accordingly.
